version: "3.8"

services:
  
  configserver:
    image: ricardodollerup/configserver:latest
    mem_limit: 700m
    ports:
     - "8071:8071"
    networks:
     - my-custom-network

  accounts:
    image: ricardodollerup/accounts:latest
    mem_limit: 700m
    ports:
     - "8080:8080"
    networks:
     - my-custom-network
    depends_on:
     - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  loans:
    image: ricardodollerup/loans:latest
    mem_limit: 700m
    ports:
     - "8090:8090"
    networks:
     - my-custom-network
    depends_on:
     - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

  cards:
    image: ricardodollerup/cards:latest
    mem_limit: 700m
    ports:
     - "9000:9000"
    networks:
     - my-custom-network
    depends_on:
     - configserver
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_CONFIG_IMPORT: configserver:http://configserver:8071/

networks:
  my-custom-network: